### ISSUE TITLE
Javascript Event for "after" load

### ISSUE THREAD

**Issue by philippfrenzel** [DarkCs/yii2-infinite-scroll#1]
Hi, 

can you implement some js-events, as I would like to fire a masonry "reorder" after a new page is loaded?

Thanks Philipp

**Comment by DarkCs** [comment]
Hi. It is a good idea, i'll think about it.

**Comment by philippfrenzel** [comment]
great! kop has a similar extension, which has some "bugs" - as I think your implementation looks more stable, i would love to switch over...

**Comment by DarkCs** [comment]
I have added a couple of events https://github.com/DarkCs/yii2-infinite-scroll/commit/4fed6e65cfe0a18323103c0c7b76d1d1f9930409 (infinitescroll:afterStart, infinitescroll:afterStop, infinitescroll:afterRetrieve)

**Comment by philippfrenzel** [comment]
:+1: cool, I'll test it and let you know how it works out in my sample project

**Comment by philippfrenzel** [comment]
works like charm! Thanks! www.fleur-et-fee.at ;)
