### ISSUE TITLE
How I can hide the pagination block

### ISSUE THREAD

**Issue by denisvasyanin** [DarkCs/yii2-infinite-scroll#2]
Hello! 
Your widget is extremely helpful though I have one question:
how I can hide the pagination block without doing something like that:
    $('.list-view').on('infinitescroll:afterStop', function(){
        if($.fn.infinitescroll) $.fn.infinitescroll('hidePagination');
    })
? 
![image](https://cloud.githubusercontent.com/assets/6671446/7513099/2e8d1396-f4ba-11e4-9930-ca691b5e3964.png)

**Comment by DarkCs** [comment]
Hi.
If you don't need to show the pagination block at all, then you can hide it with CSS

**Comment by philippfrenzel** [comment]
Yes, with css it works fine and easy!

**Comment by denisvasyanin** [comment]
Thanks
