### ISSUE TITLE
i have a problem in infinite scroll in yii2

### ISSUE THREAD

**Issue by Jack093mindset** [DarkCs/yii2-infinite-scroll#4]
In model:
 public function pagination()
    {
      $query = Events::find()->where(['>','event_created_on' , Yii::$app->formatter->asDate('now', 'yyyy-MM-dd') ]);
      $pagination = new Pagination([
         'defaultPageSize' => 4,
         'totalCount' => $query->count(),
         ]);
        return $pagination;
    }

jquery
Infinite scroll:
 $container.infinitescroll({
        navSelector: '.pagination',
        nextSelector: '.next a',
        itemSelector: '.masonry-item',
        loading: {
            msgText: '',
            finishedMsg: 'No more results found.',
            img: 'http://www.fahrschule-wallisellen.ch/img/diverses/preloader.gif'
        }
});

in index page i use to id to get the infinite scroll.
problem:
I want to stop the last page data in this..
is it possible or not...Juz Inform as soon

**Comment by DarkCs** [comment]
Sorry, seems like you are using another extension, this one does not related to https://github.com/infinite-scroll/infinite-scroll. Try to get help there or find out which yii2 extension you have.
