### ISSUE TITLE
Hidden pagination

### ISSUE THREAD

**Issue by panchenkodv** [DarkCs/yii2-infinite-scroll#6]
Hello! Can you do some external attribute, that if set "true" than pagination is not hide. A want use both scroll on button "Load more" and pagination links. Thanks!

P.S. It will be nice to be able to edit attribute "LoadingText" and its class.

**Comment by DarkCs** [comment]
Привет. Ничего что я по-русски? Отключить скрытие пагинации можно через css, `.pagination {display: block !important;}` или что-то вроде этого.
Текст загрузки и класс блока-обертки настраивается в опциях jquery плагина https://github.com/DarkCs/yii2-infinite-scroll/blob/master/assets/jquery.infinitescroll.js#L10
Через виджет их можно заменить так:

``` php
<?= \yii\widgets\ListView::widget([
    'dataProvider' => $dataProvider,
    'itemView' => '_item',
    'options' => [
        'class' => 'js-gallery',
    ],
    'itemOptions' => [
        'tag' => false,
    ],
    'summary' => false,
    'layout' => '<div class="grid-sizer"></div>{items}<div class="pagination-wrap">{pager}</div>',
    'pager' => [
        'class' => \darkcs\infinitescroll\InfiniteScrollPager::className(),
        'paginationSelector' => '.pagination-wrap',
        'pjaxContainer' => $pjax->id,
        'itemSelector' => '.js-test',
        'containerSelector' => '.js-gallery',
        'wrapperSelector' => '.js-gallery-wrapper',
        'bufferPx' => 100,
        'pluginOptions' => [
            'loadingText' => [
                '<img src="https://developer.github.com/assets/images/logo_developer.png">', // содержимое блока-визуализации загрузки
            ]
        ]
    ],
]) ?>
```

**Comment by panchenkodv** [comment]
Спасибо. Помогло =)
